/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSessionsRouteImport } from './routes/_authenticated/sessions'
import { Route as AuthenticatedRequestsRouteImport } from './routes/_authenticated/requests'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedMessagesIndexRouteImport } from './routes/_authenticated/messages.index'
import { Route as AuthenticatedMentorsIndexRouteImport } from './routes/_authenticated/mentors.index'
import { Route as AuthenticatedGrantsIndexRouteImport } from './routes/_authenticated/grants.index'
import { Route as AuthenticatedCommunityIndexRouteImport } from './routes/_authenticated/community.index'
import { Route as AuthenticatedMessagesIdRouteImport } from './routes/_authenticated/messages.$id'
import { Route as AuthenticatedMentorsIdRouteImport } from './routes/_authenticated/mentors.$id'
import { Route as AuthenticatedGrantsIdRouteImport } from './routes/_authenticated/grants.$id'
import { Route as AuthenticatedCommunityIdRouteImport } from './routes/_authenticated/community.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSessionsRoute = AuthenticatedSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRequestsRoute = AuthenticatedRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesIndexRoute =
  AuthenticatedMessagesIndexRouteImport.update({
    id: '/messages/',
    path: '/messages/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMentorsIndexRoute =
  AuthenticatedMentorsIndexRouteImport.update({
    id: '/mentors/',
    path: '/mentors/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGrantsIndexRoute =
  AuthenticatedGrantsIndexRouteImport.update({
    id: '/grants/',
    path: '/grants/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommunityIndexRoute =
  AuthenticatedCommunityIndexRouteImport.update({
    id: '/community/',
    path: '/community/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesIdRoute = AuthenticatedMessagesIdRouteImport.update({
  id: '/messages/$id',
  path: '/messages/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMentorsIdRoute = AuthenticatedMentorsIdRouteImport.update({
  id: '/mentors/$id',
  path: '/mentors/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGrantsIdRoute = AuthenticatedGrantsIdRouteImport.update({
  id: '/grants/$id',
  path: '/grants/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommunityIdRoute =
  AuthenticatedCommunityIdRouteImport.update({
    id: '/community/$id',
    path: '/community/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/requests': typeof AuthenticatedRequestsRoute
  '/sessions': typeof AuthenticatedSessionsRoute
  '/community/$id': typeof AuthenticatedCommunityIdRoute
  '/grants/$id': typeof AuthenticatedGrantsIdRoute
  '/mentors/$id': typeof AuthenticatedMentorsIdRoute
  '/messages/$id': typeof AuthenticatedMessagesIdRoute
  '/community/': typeof AuthenticatedCommunityIndexRoute
  '/grants/': typeof AuthenticatedGrantsIndexRoute
  '/mentors/': typeof AuthenticatedMentorsIndexRoute
  '/messages/': typeof AuthenticatedMessagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/requests': typeof AuthenticatedRequestsRoute
  '/sessions': typeof AuthenticatedSessionsRoute
  '/community/$id': typeof AuthenticatedCommunityIdRoute
  '/grants/$id': typeof AuthenticatedGrantsIdRoute
  '/mentors/$id': typeof AuthenticatedMentorsIdRoute
  '/messages/$id': typeof AuthenticatedMessagesIdRoute
  '/community': typeof AuthenticatedCommunityIndexRoute
  '/grants': typeof AuthenticatedGrantsIndexRoute
  '/mentors': typeof AuthenticatedMentorsIndexRoute
  '/messages': typeof AuthenticatedMessagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/requests': typeof AuthenticatedRequestsRoute
  '/_authenticated/sessions': typeof AuthenticatedSessionsRoute
  '/_authenticated/community/$id': typeof AuthenticatedCommunityIdRoute
  '/_authenticated/grants/$id': typeof AuthenticatedGrantsIdRoute
  '/_authenticated/mentors/$id': typeof AuthenticatedMentorsIdRoute
  '/_authenticated/messages/$id': typeof AuthenticatedMessagesIdRoute
  '/_authenticated/community/': typeof AuthenticatedCommunityIndexRoute
  '/_authenticated/grants/': typeof AuthenticatedGrantsIndexRoute
  '/_authenticated/mentors/': typeof AuthenticatedMentorsIndexRoute
  '/_authenticated/messages/': typeof AuthenticatedMessagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/profile'
    | '/requests'
    | '/sessions'
    | '/community/$id'
    | '/grants/$id'
    | '/mentors/$id'
    | '/messages/$id'
    | '/community/'
    | '/grants/'
    | '/mentors/'
    | '/messages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/profile'
    | '/requests'
    | '/sessions'
    | '/community/$id'
    | '/grants/$id'
    | '/mentors/$id'
    | '/messages/$id'
    | '/community'
    | '/grants'
    | '/mentors'
    | '/messages'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/_authenticated/requests'
    | '/_authenticated/sessions'
    | '/_authenticated/community/$id'
    | '/_authenticated/grants/$id'
    | '/_authenticated/mentors/$id'
    | '/_authenticated/messages/$id'
    | '/_authenticated/community/'
    | '/_authenticated/grants/'
    | '/_authenticated/mentors/'
    | '/_authenticated/messages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sessions': {
      id: '/_authenticated/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AuthenticatedSessionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/requests': {
      id: '/_authenticated/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AuthenticatedRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/': {
      id: '/_authenticated/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof AuthenticatedMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mentors/': {
      id: '/_authenticated/mentors/'
      path: '/mentors'
      fullPath: '/mentors/'
      preLoaderRoute: typeof AuthenticatedMentorsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/grants/': {
      id: '/_authenticated/grants/'
      path: '/grants'
      fullPath: '/grants/'
      preLoaderRoute: typeof AuthenticatedGrantsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/community/': {
      id: '/_authenticated/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof AuthenticatedCommunityIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/$id': {
      id: '/_authenticated/messages/$id'
      path: '/messages/$id'
      fullPath: '/messages/$id'
      preLoaderRoute: typeof AuthenticatedMessagesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mentors/$id': {
      id: '/_authenticated/mentors/$id'
      path: '/mentors/$id'
      fullPath: '/mentors/$id'
      preLoaderRoute: typeof AuthenticatedMentorsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/grants/$id': {
      id: '/_authenticated/grants/$id'
      path: '/grants/$id'
      fullPath: '/grants/$id'
      preLoaderRoute: typeof AuthenticatedGrantsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/community/$id': {
      id: '/_authenticated/community/$id'
      path: '/community/$id'
      fullPath: '/community/$id'
      preLoaderRoute: typeof AuthenticatedCommunityIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRequestsRoute: typeof AuthenticatedRequestsRoute
  AuthenticatedSessionsRoute: typeof AuthenticatedSessionsRoute
  AuthenticatedCommunityIdRoute: typeof AuthenticatedCommunityIdRoute
  AuthenticatedGrantsIdRoute: typeof AuthenticatedGrantsIdRoute
  AuthenticatedMentorsIdRoute: typeof AuthenticatedMentorsIdRoute
  AuthenticatedMessagesIdRoute: typeof AuthenticatedMessagesIdRoute
  AuthenticatedCommunityIndexRoute: typeof AuthenticatedCommunityIndexRoute
  AuthenticatedGrantsIndexRoute: typeof AuthenticatedGrantsIndexRoute
  AuthenticatedMentorsIndexRoute: typeof AuthenticatedMentorsIndexRoute
  AuthenticatedMessagesIndexRoute: typeof AuthenticatedMessagesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRequestsRoute: AuthenticatedRequestsRoute,
  AuthenticatedSessionsRoute: AuthenticatedSessionsRoute,
  AuthenticatedCommunityIdRoute: AuthenticatedCommunityIdRoute,
  AuthenticatedGrantsIdRoute: AuthenticatedGrantsIdRoute,
  AuthenticatedMentorsIdRoute: AuthenticatedMentorsIdRoute,
  AuthenticatedMessagesIdRoute: AuthenticatedMessagesIdRoute,
  AuthenticatedCommunityIndexRoute: AuthenticatedCommunityIndexRoute,
  AuthenticatedGrantsIndexRoute: AuthenticatedGrantsIndexRoute,
  AuthenticatedMentorsIndexRoute: AuthenticatedMentorsIndexRoute,
  AuthenticatedMessagesIndexRoute: AuthenticatedMessagesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
